service: minlab-transcript

plugins:
  - serverless-webpack

package:
  exclude:
    - node_modules/**/aws-sdk/**
    - ./src/**/*.spec.*
    - .eslintrc*
    - .prettierrc*
    - .vscode*
    - README*
    - ./**/__tests__/**
    - .env

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:DeleteObject
      Resource: 
        - "arn:aws:s3:::minlab-audio-transcript-input/*"
        - "arn:aws:s3:::minlab-audio-transcript-output/*"
    - Effect: Allow
      Action:
        - transcribe:StartTranscriptionJob
        - transcribe:GetTranscriptionJob
        - transcribe:DeleteTranscriptionJob
      Resource: "*"

functions:
  getUploadURL:
    handler: handler.getUploadURL
    events:
      - http:
          path: uploadURL
          method: get
          cors: true

  transcribeAudio:
    handler: handler.transcribeAudio
    events:
      - s3:
          bucket: minlab-audio-transcript-input
          event: s3:ObjectCreated:*
          existing: true

  getTranscript:
    handler: handler.getTranscript
    events:
      - http:
          path: transcript/{id}
          method: get
          cors: true

resources:
  Resources:
    audioTranscriptInputBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: minlab-audio-transcript-input
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"
              AllowedMethods:
                - "PUT"


    audioTranscriptOutputBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: minlab-audio-transcript-output